
import { GoogleGenAI, GenerateContentResponse, Type } from "@google/genai";

// Ensure the API key is available. In a real app, you'd have more robust error handling.
if (!process.env.API_KEY) {
  throw new Error("API_KEY environment variable not set");
}

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

export async function generateMangaImage(prompt: string): Promise<string> {
  try {
    const response = await ai.models.generateImages({
        model: 'imagen-4.0-generate-001',
        prompt: prompt,
        config: {
          numberOfImages: 1,
          outputMimeType: 'image/png',
          aspectRatio: '1:1',
        },
    });

    if (response.generatedImages && response.generatedImages.length > 0) {
      const base64ImageBytes = response.generatedImages[0].image.imageBytes;
      return base64ImageBytes;
    } else {
      throw new Error('No image was generated by the API.');
    }
  } catch (error) {
    console.error("Error generating image with Gemini API:", error);
    // Re-throw the error to be handled by the calling function
    throw error;
  }
}


export async function generateText(prompt: string): Promise<string> {
    try {
        const response: GenerateContentResponse = await ai.models.generateContent({
            model: 'gemini-2.5-pro',
            contents: prompt,
        });
        return response.text;
    } catch (error) {
        console.error("Error generating text with Gemini API:", error);
        throw error;
    }
}

export async function generateStructuredText<T>(
  prompt: string,
  responseSchema: any // Simplified for this example
): Promise<T> {
  try {
    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash",
      contents: prompt,
      config: {
        responseMimeType: "application/json",
        responseSchema: responseSchema,
      },
    });

    // Clean the response to ensure it's valid JSON before parsing
    const jsonStr = response.text.trim().replace(/^```json\s*|```$/g, '');
    return JSON.parse(jsonStr) as T;
  } catch (error) {
    console.error("Error generating structured text:", error);
    throw error;
  }
}
