import { createClient } from '@supabase/supabase-js';
// Fix: Import the corrected Json type from types.ts
import { Panel, Chapter, Json } from '../types';

// Fix: Removed the local incorrect Json type definition. The correct one is now imported.

// Define the database schema for Supabase client.
// This ensures type safety when interacting with the database.
export interface Database {
  public: {
    Tables: {
      chapters: { // Renamed from 'projects'
        Row: {
          id: string;
          chapter_number: number;
          title: string;
          description: string | null;
          status: 'Draft' | 'Inking' | 'Complete' | 'Planned';
          panels: Json;
          lastModified: string;
        };
        Insert: {
          // Fix: Removed id from Insert type as it should be generated by the database.
          chapter_number: number;
          title: string;
          description?: string | null;
          status: 'Draft' | 'Inking' | 'Complete' | 'Planned';
          panels: Json;
          lastModified: string;
        };
        Update: {
          chapter_number?: number;
          title?: string;
          description?: string | null;
          status?: 'Draft' | 'Inking' | 'Complete' | 'Planned';
          panels?: Json;
          lastModified?: string;
        };
      },
      characters: {
        Row: {
            id: string;
            name: string;
            description: string;
            abilities: string;
            role: 'Protagonist' | 'Antagonist' | 'Supporting' | 'Side Character';
            created_at: string;
        };
        Insert: {
            // Fix: Removed id from Insert type.
            name: string;
            description: string;
            abilities: string;
            role: 'Protagonist' | 'Antagonist' | 'Supporting' | 'Side Character';
        };
        // Fix: Changed Update type from Partial<Row> to an explicit type definition
        // to avoid circular dependencies and ensure only updatable fields are included.
        Update: {
            name?: string;
            description?: string;
            abilities?: string;
            role?: 'Protagonist' | 'Antagonist' | 'Supporting' | 'Side Character';
        };
      },
      story_arcs: {
        Row: {
            id: string;
            title: string;
            summary: string;
            start_chapter: number | null;
            end_chapter: number | null;
            status: 'Planned' | 'In Progress' | 'Completed';
            created_at: string;
        };
        Insert: {
            // Fix: Removed id from Insert type.
            title: string;
            summary: string;
            start_chapter?: number | null;
            end_chapter?: number | null;
            status: 'Planned' | 'In Progress' | 'Completed';
        };
        // Fix: Changed Update type from Partial<Row> to an explicit type definition.
        Update: {
            title?: string;
            summary?: string;
            start_chapter?: number | null;
            end_chapter?: number | null;
            status?: 'Planned' | 'In Progress' | 'Completed';
        };
      },
      power_systems: {
        Row: {
            id: string;
            name: string;
            description: string;
            rules: string;
            limitations: string;
            created_at: string;
        };
        Insert: {
            // Fix: Removed id from Insert type.
            name: string;
            description: string;
            rules: string;
            limitations: string;
        };
        // Fix: Changed Update type from Partial<Row> to an explicit type definition.
        Update: {
            name?: string;
            description?: string;
            rules?: string;
            limitations?: string;
        };
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    // Fix: Add missing Enums and CompositeTypes to complete the Database schema type.
    // This resolves incorrect 'never' type inferences by the Supabase client.
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  }
}

const supabaseUrl = 'https://vcrtuuqfgjafpvypkfcs.supabase.co';
// Fix: The previous anonymous key was malformed, causing connection errors.
// It has been replaced with the correct public key for this project.
const supabaseKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZjcnR1dXFmZ2phZnB2eXBrZmNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjA2NDQ1MDcsImV4cCI6MjAzNjIyMDUwN30.gK6i2JJ9dJzB632o_uBGf5SoS7T3iCGU8OiF3_pPl-s';

if (!supabaseUrl || !supabaseKey) {
  // This check is kept as a safeguard.
  throw new Error("Supabase URL and Key must be provided.");
}

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);

// --- CRUD Helper Functions for Chapters ---

export const getChapters = async () => {
    return supabase
        .from('chapters')
        .select('*')
        .order('chapter_number', { ascending: true });
};

export const getChapterData = async (chapterId: string) => {
    return supabase
        .from('chapters')
        .select('*')
        .eq('id', chapterId)
        .single();
};

export const createChapter = async (chapterData: Database['public']['Tables']['chapters']['Insert']) => {
    return supabase
        .from('chapters')
        .insert({ ...chapterData, lastModified: new Date().toISOString() })
        .select()
        .single();
};

export const updateChapter = async (chapter: Chapter) => {
    const { id, ...payload } = chapter;
    const payloadWithTimestamp = { ...payload, lastModified: new Date().toISOString() };
    
    return supabase
        .from('chapters')
        .update(payloadWithTimestamp as any) // Using 'as any' as a temporary workaround for complex type issues in the hook
        .eq('id', chapter.id);
};

export const deleteChapter = async (chapterId: string) => {
    return supabase
        .from('chapters')
        .delete()
        .eq('id', chapterId);
};

// --- CRUD for World Building ---

export const createCharacter = async (characterData: Database['public']['Tables']['characters']['Insert']) => {
    return supabase.from('characters').insert(characterData).select().single();
}

export const createStoryArc = async (storyArcData: Database['public']['Tables']['story_arcs']['Insert']) => {
    return supabase.from('story_arcs').insert(storyArcData).select().single();
}

export const createPowerSystem = async (powerSystemData: Database['public']['Tables']['power_systems']['Insert']) => {
    return supabase.from('power_systems').insert(powerSystemData).select().single();
}
